containerd: Autospec creation for update from version 1.6.8 to version 1.6.14
Akhil Mohan (5):
      retry request on writer reset
      update codeql-action to v2
      support fetching containerd from non public GCS buckets
      disable tracing while handling token
      Revert "[release/1.6] support fetching containerd from non public GCS buckets"

Akihiro Suda (3):
      update runc binary to v1.1.4
      CI: update GHA instances from Ubuntu 18.04 to 20.04
      cri: fix `memory.memsw.limit_in_bytes: no such file or directory`

Andrey Klimentyev (1):
      Do not append []string{""} to command to preserve Docker compatibility

Austin Vazquez (2):
      Migrate away from GitHub actions set-output
      Fix order of operations when setting lease labels

Benjamin Elder (1):
      remove stray .zuul.yaml

Danny Canter (3):
      overlayutils: Add fastpath for userxattr check
      Prepare release notes for v1.6.10
      CRI stream server: Fix goroutine leak in Exec

Derek McGowan (4):
      Prepare release notes for v1.6.11
      Prepare release notes for v1.6.12
      Prepare release notes for v1.6.13
      Prepare release notes for v1.6.14

Gavin Inglis (2):
      ctr import: strictly match platform
      allow client to remove created tasks with PID 0

Henry Wang (1):
      adding support of CAP_BPF and CAP_PERFMON

Iceber Gu (1):
      remotes/docker/config: Skipping TLS verification for localhost

Kathryn Baldauf (1):
      [release/1.6] go.mod: Bump hcsshim to v0.9.5

Kazuyoshi Kato (3):
      [release/1.6] upgrade containerd/continuity from v0.2.2 to v0.3.0
      [release/1.6] Stats() shouldn't assume s.container is non-nil
      Upgrade actions/upload-artifact from v2 to v3

Kirtana Ashok (2):
      Added nullptr checks to pkg/cri/server and sbserver
      Bump hcsshim to v0.9.6

Maksym Pavlenko (4):
      Fix cleanup in critest
      Fix linter warnings
      Rework permission handling in scripts
      Use global env variable to specify Go version on CI

Mathis Michel (1):
      fix: check for tmpfs when evaluating if userxattr should be used

Mike Brown (1):
      nil check to avoid panic on upgrade

Paco Xu (1):
      migrate from k8s.gcr.io to registry.k8s.io

Phil Estes (1):
      Move up actions versions to prep for deprecation

Qasim Sarfraz (2):
      cri: add pod uid annotation
      cri: make swapping disabled with memory limit

Qiutong Song (3):
      Persist container and sandbox if resource cleanup fails, like teardownPodNetwork
      Add integration tests with failpoint
      Update container with sandbox metadata after NetNS is created

Samuel Karp (5):
      ci: remove GOPROXY environment variable due to https://github.com/go-yaml/yaml/issues/887
      archive: validate digests before use
      cri: PodSandboxStatus should tolerate missing task
      Update mailmap
      Prepare release notes for v1.6.9

Sebastiaan van Stijn (9):
      oci: WithDefaultUnixDevices(): remove tun/tap from the default devices
      vendor: golang.org/x/crypto v0.0.0-20220315160706-3147a52a75dd
      [release/1.6] integration: remove use of deprecated io/ioutil
      [release/1.6] gofmt with go1.19
      [release/1.6] update golangci-lint to v1.19.0
      [release/1.6] Update go 1.18.7, addresses CVE-2022-2879, CVE-2022-2880, CVE-2022-41715
      [release/1.6] update to Go 1.18.8 to address CVE-2022-41716
      [release/1.6] go.mod: use golang_protobuf_extensions v1.0.4
      [release/1.6] update to go1.18.9

Shinichi Morimoto (1):
      fix pool_device_test.go

Sophie Liu (1):
      Add logging volume metrics to Containerd CRI plugin

Wei Fu (10):
      .zuul: remove the zuul because it is offline
      pkg/failpoint: init failpoint package
      runtime/v2: manager supports server interceptor
      bin/ctr,integration: new runc-shim with failpoint
      runtime/v2/shim: return if error in load plugin
      pkg/failpoint: add DelegatedEval API
      integration: CNI bridge wrapper with failpoint
      integration: Add injected failpoint testing for RunPodSandbox
      pkg/failpoint: add FreeBSD link and update pkg doc
      integration: simplify CNI-fp and add README.md

Yasin Turan (1):
      ctr export strictly match default platform

Ye Sijun (1):
      make xattr EPERM non-fatal in createTarFile

chaunceyjiang (1):
      fatal error: concurrent map iteration and map write

cosmoer (1):
      fix: support simultaneous create diff for same parent snapshot

lengrongfu (1):
      fix pusher concurrent close channel

ruiwen-zhao (3):
      Update CRI-API
      ContainerStatus to return container resources
      Set grpc code for unimplemented cri-api methods

zounengren (2):
      bump cri-api
      update intergration